name: Conventional Commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: liatrio/github-actions/conventional-pr-title@conventional-pr-title-breaking
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
